name: footflare
description: "FootFlare Flutter Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

    - assets/logo_brand/
    - assets/kategory/
    - assets/product/
    - assets/icon/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-ExtraBold.ttf
          weight: 800

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500