name: footflare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Library untuk mengambil foto dari galeri/kamera di halaman Edit Profile
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Konfigurasi Assets Gambar
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  # Konfigurasi Custom Fonts (Jost & Inter)
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500